### PR TITLE
164 - SPIKE (and Survival) Keywords

### PR DESCRIPTION
**Pull request by DefinitelyNotJT**
SPIKE keywords forwarded into the plugin.
SPIKE keywords added to armor and weapons.
Also added "missing" survival keywords. Generally followed WACCF's example on this, but intentionally omitted "warm" keywords for Ebony and Daedric (to differentiate them from the warmer-looking Stalhrim / Dragonbone respectively, on the same tiers - dunno if you want to add those or not).

Ancano's Robes:						Survival_ArmorWarm, Survival_BodyAndHead
Aicantar's Dwarven Cuirass:				SPIKEArmorDwarven
Ancient Dragonplate Cuirass:			SPIKEArmorDragonBone
Ancient Nord Cuirass:					Survival_ArmorCold
Ancient Nord Boots:						Survival_ArmorWarm
Blood Horker Cuirass:					SPIKEArmorIron, Survival_ArmorWarm
Blood Horker Boots:						Survival_ArmorWarm
Blood Horker Gauntlets:					Survival_ArmorWarm
Blood Horker Helmet:					Survival_ArmorWarm
Chieftain Cuirass:						SPIKEArmorOrcish
Daedric Cuirass:						SPIKEArmorFancyBlack
Dragonplate Cuirass:					SPIKEArmorDragonBone
Dremora Pirate Cuirass:					SPIKEArmorFancyBlack
Daedric Cuirass (Dremora):				SPIKEArmorFancyBlack
Dwarven Heavy Cuirass:					SPIKEArmorDwarven
Ebony Cuirass:							SPIKEArmorEbony
Falmer Heavy Cuirass:					SPIKEArmorStinksDeath
Reinforced Eastmarch Guard Cuirass:		SPIKEArmorSons, Survival_ArmorWarm
Reinforced Hjaalmarch Guard Cuirass:	Survival_ArmorWarm
Reinforced The Pale Guard Cuirass:		Survival_ArmorWarm
Reinforced Winterhold Guard Cuirass:	Survival_ArmorWarm
Halvar's Cuirass:						SPIKEArmorSteel, SPIKEArmorSteelPlate
Iron Cuirass:							SPIKEArmorIron, Survival_ArmorCold
Iron Cuirass (Pauldrons):				SPIKEArmorIron, SPIKEArmorMerc
Orcish Heavy Cuirass:					SPIKEArmorOrcish
Quicksilver Cuirass:					SPIKEArmorTrueNord, Survival_ArmorWarm
Quicksilver Boots: 						Survival_ArmorWarm
Quicksilver Gauntlets:					Survival_ArmorWarm
Silver Hand Veteran Cuirass:			SPIKEArmorSteel
Silver Hand Cuirass:					SPIKEArmorSteel
Stalhrim Heavy Cuirass:					Survival_ArmorWarm
Stalhrim Heavy Boots:					Survival_ArmorWarm
Stalhrim Heavy Gauntlets:				Survival_ArmorWarm
Stalhrim Heavy Helmet:					Survival_ArmorWarm
Steel Plate Cuirass:					SPIKEArmorSteel, SPIKEArmorSteelPlate
Steel Cuirass:							SPIKEArmorSteel
Steel Cuirass (Pauldrons):				SPIKEArmorSteel
Stormcloak Officer Cuirass:				SPIKEArmorSonsBear, Survival_ArmorWarm
Stormcloak Officer Boots:				Survival_ArmorWarm
Stormcloak Officer Gauntlets:			Survival_ArmorWarm
Stormcloak Officer Helmet:				Survival_ArmorWarm
The Skinner's Cuirass:					SPIKEArmorSteel
Tyranus' Cuirass:						SPIKEArmorSteel, SPIKEArmorSteelPlate
Vigilant Cuirass:						SPIKEArmorIron
Vvardenfell Ebony Cuirass:				SPIKEArmorEbony
Wolf Cuirass:							Survival_ArmorWarm
Wolf Boots:							Survival_ArmorWarm
Wolf Gauntlets:						Survival_ArmorWarm

Alain's Elven Cuirass:					Survival_ArmorWarm (*)
Alain's Elven Boots:					Survival_ArmorWarm (*)
Alain's Elven Gauntlets:				Survival_ArmorWarm (*)
Alik'r Cuirass:							SPIKERedguardMerc
Ancient Dragonscale Cuirass:			SPIKEArmorDragonScale
Blackguard Cuirass:						SPIKEArmorThievesGuild, Survival_ArmorCold
Dawnguard Light Cuirass (Red):			Survival_ArmorCold (**)
Dragonscale Cuirass:					SPIKEArmorDragonScale
Dwarven Light Cuirass:					SPIKEArmorDwarven
Executioner Cuirass:					Survival_ArmorCold
Executioner Boots:						Survival_ArmorWarm
Executioner Gauntlets:					Survival_ArmorWarm
Falmer Light Cuirass:					SPIKEArmorStinksDeath
Forsworn Cuirass:						SPIKEArmorWeak
Glass Gauntlets:						Survival_ArmorWarm
Hide Cuirass:							SPIKEArmorLeather, SPIKEArmorWeak, Survival_ArmorCold
Hide Cuirass (Studded):					SPIKEArmorBrigand, Survival_ArmorCold
Hide Boots:							Survival_ArmorWarm
Hade Bracers:							Survival_ArmorCold
Imperial Light Cuirass:					SPIKEArmorImperialScout
Imperial Studded Cuirass:				SPIKEArmorImperial
General Tullius' Cuirass:				SPIKEArmorImperial, SPIKEImperialLegate, Survival_ArmorCold
Imperial Light Bracers:					Survival_ArmorCold
Leather Cuirass:						SPIKEArmorLeather
Leather Bracers:						Survival_ArmorCold
Linwe's Cuirass:						Survival_ArmorCold (**)
Morag Tong Cuirass:					SPIKEArmorAssassin
Netch Leather Cuirass:					SPIKEArmorLeather
Boiled Netch Leather Cuirass:			SPIKEArmorLeather
Orcish Light Cuirass:					SPIKEArmorOrcish
Penitus Oculatus Cuirass:				SPIKEArmorImperialSecurity
Scale Cuirass:							SPIKEArmorScaleShiny
Scale Cuirass (Horn):					SPIKEArmorScaleShiny
Scale Boots:							Survival_ArmorWarm
Shrouded Cuirass (Sleeveless):			Survival_ArmorCold (**)
Ancient Falmer Cuirass:					Survival_ArmorCold
Ancient Falmer Cuirass (Pauldrons):		Survival_ArmorCold
Stalhrim Light Cuirass:					Survival_ArmorWarm
Stalhrim Light Boots:					Survival_ArmorWarm
Stalhrim Light Gauntlets:				Survival_ArmorWarm
Stalhrim Light Helmet:					Survival_ArmorWarm
Stormcloak Cuirass:						SPIKEArmorSons
Fur Gauntlets (Guard):					Survival_ArmorWarm (***)
Ulfric's Cuirass:						Survival_ArmorWarm
Ulfric's Boots:							Survival_ArmorWarm
Ulfric's Gauntlets:						Survival_ArmorWarm	
Vampire Cuirass (all variants):			SPIKEArmorStinksDeath

Deathbrand Cuirass:						Survival_ArmorWarm
Deathbrand Boots:						Survival_ArmorWarm
Deathbrand Gauntlets:					Survival_ArmorWarm
Deathbrand Helmet:						Survival_ArmorWarm
Gloves of the Pugilist:					Survival_ArmorWarm

Ancient Nord Dagger:					SPIKEWeapPigsticker
Ancient Nord Shortsword:				SPIKEWeapPigsticker
Ancient Nord Sword:					SPIKEWeapPigsticker
Daedric Dai-Katana:						SPIKEWeapFancySwordBlack
Daedric Greatsword:						SPIKEWeapFancySwordBlack
Daedric Katana:						SPIKEWeapFancySwordBlack
Daedric Shortsword:						SPIKEWeapFancySwordBlack
Daedric Sword:							SPIKEWeapFancySwordBlack
Daedric Wakizashi:						SPIKEWeapFancySwordBlack
Ebony Dai-Katana:						SPIKEWeapFancySwordBlack
Ebony Greatsword:						SPIKEWeapFancySwordBlack
Ebony Katana:							SPIKEWeapFancySwordBlack
Ebony Sword:							SPIKEWeapFancySwordBlack
Ebony Shortsword:						SPIKEWeapFancySwordBlack
Ebony Wakizashi:						SPIKEWeapFancySwordBlack
Elven Dagger:							SPIKEWeapElvenBlade
Elven Dai-Katana:						SPIKEWeapElvenBlade
Elven Greatsword:						SPIKEWeapElvenBlade (****)
Elven Katana:							SPIKEWeapElvenBlade
Elven Shortsword:						SPIKEWeapElvenBlade
Elven Sword:							SPIKEWeapElvenBlade
Elven Tanto:							SPIKEWeapElvenBlade
Elven Wakizashi:						SPIKEWeapElvenBlade
Imperial Dagger:						SPIKEWeapPigsticker
Imperial Shortsword:					SPIKEWeapPigsticker				
Imperial Sword:						SPIKEWeapPigsticker
Iron Dagger:							SPIKEWeapPigsticker
Iron Greatsword:						SPIKEWeapIronSword
Iron Shortsword:						SPIKEWeapIronSword, SPIKEWeapPigsticker
Iron Sword:							SPIKEWeapIronSword, SPIKEWeapPigsticker
Skyforge Steel Dagger:					SPIKEWeapPigsticker
Skyforge Steel Greatsword:				SPIKEWeapSteelSword
Skyforge Steel Shortsword:				SPIKEWeapSteelSword
Skyforge Steel Sword:					SPIKEWeapSteelSword
Steel Dagger:							SPIKEWeapPigsticker
Steel Dai-Katana:						SPIKEWeapSteelSword
Steel Greatsword:						SPIKEWeapSteelSword
Steel Katana:							SPIKEWeapSteelSword
Steel Shortsword:						SPIKEWeapSteelSword
Steel Sword:							SPIKEWeapSteelSword
Steel Tanto:							SPIKEWeapPigsticker
Steel Wakizashi:						SPIKEWeapSteelSword

Miraak's Sword:						SPIKEWeapFoul
Borvir's Dagger:						SPIKEWeapElvenBlade (****)
Prelate's Dagger:						SPIKEWeapElvenBlade (****)
Alessandra's Dagger:					SPIKEWeapPigsticker
Jon's Twohander:						SPIKEWeapIronSword
Amren's Family Sword:					SPIKEWeapIronSword
Iron Lunar Sword:						SPIKEWeapIronSword
Bloodthorn:							SPIKEWeapPigsticker
Rundi's Dagger:						SPIKEWeapPigsticker
Valdr's Lucky Dagger:					SPIKEWeapPigsticker
Balgruuf's Greatsword:					SPIKEWeapSteelSword
Harrald's Steel Sword:					SPIKEWeapSteelSword
Steel Lunar Sword:						SPIKEWeapSteelSword
Queen Freydis' Sword:					SPIKEWeapSteelSword
Ragnok's Toothpick:						SPIKEWeapSteelSword

*	Normal Elven does not have warmth bonus, but this (the CC version at least) looks more padded, and I figure makes it more "special" 
**	Following WACCF's example, sleeveless variants have cold keyword. 
***	Update.esm assigns this the "cold" keyword, but looking at the actual item this MUST be a mistake. WACCF also changes it to warm.
****	Also fixed sounds (forward from WACCF)

### CODE REVIEW

**Comment by ProbablyManuel** [comment]
### SPIKE

- Since Guard Dialogue Overhaul no longer adds keywords to any vanilla item, Requiem should not forward these keywords to vanilla records.
- Should Vigilant, Silver Hand, and Netch Leather armors really get the standard material comments?
- Should Imperial and Steel weapons really get the pigsticker comments? I'm aware GDO does this too, but this feels like an oversight in the mod.

### Survival Keywords

I'm not convinced by the specific keyword assignments such as Ancient Nord Cuirass being cold and Ancient Nord Boots being warm.

1. Consequently, other stats like armor rating or weight should also be determined on an individual basis.
2. These assignments rely on visual details in the vanilla models which may be changed by visual replacers.

I'd rather implement survival keywords per armor set like other armor traits. If this broader approach suits you too, please do this in a separate pull request. Since I'd like to directly integrate this with the scripting suite, adding a new column to [Armor.xlsx](https://github.com/ProbablyManuel/requiem/blob/main/tools/xEdit%20Scripts/patcher_data/Armor.xlsx) that denotes Warm, Cold, or Normal for each armor set would be most useful.

**Comment by DefinitelyNotJT** [comment]
> Since Guard Dialogue Overhaul no longer adds keywords to any vanilla item, Requiem should not forward these keywords to vanilla records.

Looks like [Guard Dialogue Overhaul SE](https://www.nexusmods.com/skyrimspecialedition/mods/22075) still contains the armor records in its plugin (from which WACCF carries over the keywords), but [Guard Dialogue Overhaul Redux](https://www.nexusmods.com/skyrimspecialedition/mods/20791) does not. However, looks like the conditions on guard dialogue it changes should obviate the need for the keywords (on vanilla, base game items anyway - new ones would still need them).


> Should Vigilant, Silver Hand, and Netch Leather armors really get the standard material comments?

I don't think there's any reason to _not_ have the keywords on Silver Hand and Netch Leather - the positive comments guards make about steel and leather armors wouldn't feel out of place for them, at least imo. True that Vigilant may be questionable though... it may be "iron-tier" in terms of stats but (with the CC patch at least) it looks much fancier. 


> Should Imperial and Steel weapons really get the pigsticker comments? I'm aware GDO does this too, but this feels like an oversight in the mod.

Actually agree on this. I just forwarded them in the interest of minimizing "subjective" changes, but it seemed odd to me too. Especially with how much the guards seem to appreciate "good old-fashioned steel", lol. I'd be happy to remove them.


> Survival Keywords

Personally, I like the little extra flavor of warmth, weight, armor, etc. being determined more on an individual-item basis, based on the actual appearance of the item, but I also totally get why you don't want to do that. Even doing it on a set-basis doesn't really solve the potential issue of visual replacers, but if a user is installing replacers that fundamentally change the design direction from vanilla that's really on them. 

I don't mind taking another pass at this and assigning on a whole-set basis - can I do a pull request on the Armor.xlsx file itself? (Guess I'll just try).

**Comment by ProbablyManuel** [comment]
Since Excel files are binary, editing them in a pull request is suboptimal. A simple text snippet with two columns for the set identifier (as found in the spreadsheet) and the survival keyword is generally sufficient because it can easily be pasted into the spreadsheet when needed.

If you are motivated and have some basic coding skills, you can subsequently extend the Python and xEdit script to read the additional column, and patch it into the plugin. I can give you the necessary pointers if you're interested.

**Comment by DefinitelyNotJT** [comment]
My coding skills extend to _very_ simple Papyrus stuff, unfortunately. I really should dig into Python and xEdit scripting at some point, though (xEdit scripts are in... Pascal? Is that right?) ... Maybe I will take you up on that at some point in the near future lol.

For now I'll send in a text snippet with the proposed additions!

**Comment by ProbablyManuel** [comment]
I moved the Survival keywords to a separate issue: #263

**Pull request merged**
